pipeline{
    agent any
        stage('Docker Build'){
            steps{
                sh 'docker build -t python-app:latest .'
            }
        }
        stage('Run Container'){
            steps{
                sh 'docker run -d -p 5001:5000 python-app:latest'
            }
        }
    }
}