pipeline{
    agent any
    stages{
        stage('Checkout'){
            steps{
                git 'https://github.com/pratikkamble14/python-devops.git'
            }
        }
        stage('Docker Build'){
            steps{
                sh 'docker build -t python-app:latest .'
            }
        }
        stage('Run Container'){
            steps{
                sh 'docker run -d -p 5001:5000 python-app:latest'
            }
        }
    }
}